// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                // 主键ID
	Username     string                `gorm:"column:username;comment:用户昵称" json:"username"`                                  // 用户昵称
	UserAccount  string                `gorm:"column:user_account;comment:账号" json:"user_account"`                            // 账号
	AvatarURL    string                `gorm:"column:avatar_url;comment:用户头像" json:"avatar_url"`                              // 用户头像
	Gender       int32                 `gorm:"column:gender;comment:性别" json:"gender"`                                        // 性别
	UserPassword string                `gorm:"column:user_password;not null;comment:密码" json:"user_password"`                 // 密码
	Phone        string                `gorm:"column:phone;comment:电话" json:"phone"`                                          // 电话
	Email        string                `gorm:"column:email;comment:邮箱" json:"email"`                                          // 邮箱
	UserStatus   int32                 `gorm:"column:user_status;not null;comment:用户状态 0-正常" json:"user_status"`              // 用户状态 0-正常
	CreateTime   time.Time             `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`  // 创建时间
	UpdateTime   time.Time             `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`  // 更新时间
	IsDelete     soft_delete.DeletedAt `gorm:"column:is_delete;not null;comment:是否删除（逻辑删除）;softDelete:flag" json:"is_delete"` // 是否删除（逻辑删除）
	UserRole     int32                 `gorm:"column:user_role;not null;comment:用户角色 0-普通用户 1-管理员" json:"user_role"`          // 用户角色 0-普通用户 1-管理员
	PlanetCode   string                `gorm:"column:planet_code;comment:星球编号" json:"planet_code"`                            // 星球编号
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
